### ISSUE TITLE
Dropbox install not working

### ISSUE THREAD

**Issue by manu-chroma** [manojpandey/linux-fresh-setup#12]
Hey,
The [following method](https://github.com/manojpandey/setup#dropbox) to install Dropbox doesn't seem to be working. Can you confirm ?

Base System: Ubuntu 16.04 LTS 64-bit

**Comment by manojpandey** [comment]
@akul08 Can you help out on this? :)

**Comment by akul08** [comment]
Solved. Pr sent. :+1:
