### ISSUE TITLE
Installing oh-my-zsh causes authentication Failure

### ISSUE THREAD

**Issue by ExC0d3** [manojpandey/linux-fresh-setup#4]
After successful cloning Authentication error is ecountered.

**Password: chsh: PAM: Authentication failure**

Possible solution could be downloading the script seperately and installing using bash.
Possible explanation - Piping to bash is not the same as giving the bash a parameter.

![image](https://cloud.githubusercontent.com/assets/8655624/10689343/2ba532d6-7998-11e5-9912-4fd1d13733eb.png)

**Comment by manojpandey** [comment]
You entered the wrong password apparently :)

**Comment by ExC0d3** [comment]
My SSH key's were messed up. Was still new to the system back then 
:)
